### ISSUE TITLE
Initial cards?

### ISSUE THREAD

**Issue by maryokhin** [jwasham/computer-science-flash-cards#1]
Hi,

Was inspired to go through your Google list and saw you added a reference to this project on my daily upstream merge :)

I was thinking maybe you can provide an SQLite dump of the cards that you created during studying? It would help from both the perspective of starting off quickly + cards that another person created are even more valuable to us, as you have no unconscious bias for creating cards you can answer easily.

Maybe we can take it even further and create a sharable database of cards where other people can add on the cards they created.

**Comment by jwasham** [comment]
OK, I added mine as cards-jwasham.db
Keep in mind I went overboard and have everything from assembly language and Python trivia to machine learning and statistics. It's way too much for what's required by Google.

**Comment by maryokhin** [comment]
Great, thanks, would still be interesting to take a look 👍
