### ISSUE TITLE
Docker Image Launch Issue

### ISSUE THREAD

**Issue by aspdev91** [jwasham/computer-science-flash-cards#10]
Hi, I'm attempting to use the docker image. Everything successfully builds, but when I connect to localhost:8000, its says the site can't be reached. Any solutions? Thanks!

**Comment by jwasham** [comment]
I'll leave it to @Tinpee to handle support for the Docker version. He build that portion.

**Comment by hienphamlabs** [comment]
@aspdev91, Did you run any container after built this image?
`docker run -d -p 8000:8000 --name cs-flash-cards cs-flash-cards`
