### ISSUE TITLE
Question on data

### ISSUE THREAD

**Issue by eyedol** [jwasham/computer-science-flash-cards#13]
I was feeling a bit lazy to setup the web based flash card and since I'm used to Anki and I wanted to run away with your data set, I wrote a tiny [py script](https://github.com/eyedol/tools/blob/master/anki_data_builder.py) to export the db to [csv](https://github.com/eyedol/tools/blob/master/anki-card.csv) that I can import into Anki. Hope it's okay? Let me know. Thank you for your great resources.

**Comment by jwasham** [comment]
That's a great idea. Someone else had converted my work-in-progress set to Anki back in October. 
Thanks for putting this together. I'll link to it from the README!

**Comment by eyedol** [comment]
Great to hear. Thanks for linking my work.
