### ISSUE TITLE
Flash cards app with hints support using nodejs

### ISSUE THREAD

**Issue by ashwanikumar04** [jwasham/computer-science-flash-cards#14]
Hi,
Thanks for this very helpful repo to support budding programmers. I have taken the db which you have provided and created a simple node js based application with hints. If possible please link to the repo. 
The repo is available [here](https://github.com/ashwanikumar04/flash-cards). Please let me know if you need any other info.

Thanks,
Ashwani

**Comment by ashwanikumar04** [comment]
Added a demo [here](http://demo.ashwanik.in)
Credentials: admin/demo

**Comment by jwasham** [comment]
Very nice! The demo really helps (since I was too lazy to set it up). 
I'll add a link!
