### ISSUE TITLE
SyntaxError in anki_data_builder.py?

### ISSUE THREAD

**Issue by g2178716** [jwasham/computer-science-flash-cards#15]
First of all, you're an inspiration! Thanks for telling your story and for putting all your materials out there to help others.

Maybe you can help me with the data builder script. I'm probably doing something wrong here but when I run the data converter script on Windows, I get a syntax error:

	c:\computer-science-flash-cards-master>python anki_data_builder.py ./cards-jwasham.db ./cards-jwasham.csv
	  File "anki_data_builder.py", line 5
		<!DOCTYPE html>
		^
	SyntaxError: invalid syntax

Getting these to use on my phone will be a godsend. Thanks again!

**Comment by jwasham** [comment]
Hi @g2178716 you had downloaded the script from the link, but it was a github web page. You need the raw script:
https://raw.githubusercontent.com/eyedol/tools/master/anki_data_builder.py

**Comment by g2178716** [comment]
That's embarrassing. Thanks John. And good luck on the interview. Everyone's rooting for you.

**Comment by jwasham** [comment]
Thank you!
