### ISSUE TITLE
How to open this link?

### ISSUE THREAD

**Issue by svaderia** [jwasham/computer-science-flash-cards#22]
This [link](`https://googleyasheck.com/flash-cards-site-complete/`) that you have added for a brief rundown of the site is not working!
Shows this page:
![screenshot 38](https://cloud.githubusercontent.com/assets/26005890/25012272/92cfdcd4-208d-11e7-99f1-c5bf6ca20d04.png)
After clicking to `View the Googley original here` it goes to this page:
![screenshot 37](https://cloud.githubusercontent.com/assets/26005890/25012324/c81f0fd6-208d-11e7-858a-bc26fbb0bf9f.png)

Is there any other way to open it?
Cheers! 😄

**Comment by jwasham** [comment]
Sometimes the Wayback machine can be flaky. Here's a mirror on my blog: https://startupnextdoor.com/flash-cards-site-complete/?src=gah-arch
