### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ghost** [jwasham/computer-science-flash-cards#23]
Hi jwasham,

I followed your guide but I cant run the localhost. Could you mind helping me to fix this problem ?

![image](https://cloud.githubusercontent.com/assets/15644614/25077408/a60fdaa6-2353-11e7-8aa5-d6a071070471.png)

**Comment by jwasham** [comment]
@devyash wrote that portion (I just added him to that section).
Reach out to him for help.

**Comment by devyash** [comment]
Can you provide more details?

**Comment by ympons** [comment]
Hi, thanks for this resource.

I was getting a similar error but I got inspired and I created a version of this app using Golang 😄 . The repo is available [here](https://github.com/ympons/flasher).

Cheers!

**Comment by jwasham** [comment]
Closing due to lack of requester response.

**Comment by devyash** [comment]
Hi, Can you provide more details for me to help you out?

**Comment by CharlieStras** [comment]
@HoangSonTran 

Hi, maybe you can try copy ./cards-empty.db to ./db/cards.db  :D

**Comment by akoliyot** [comment]
@CharlieStras  Your suggestion worked!
