### ISSUE TITLE
Using provided databases

### ISSUE THREAD

**Issue by dhruvparamhans** [jwasham/computer-science-flash-cards#24]
This is presumably a very silly question but how can I use the cards that you have provided in the database cards-jwasham.db? 

Is there a bit of code that I need to edit or dos it work out of the box? 

For information, I am using the app locally via the python installation. 

Thanks and cheers to you for the effort :)

**Comment by jwasham** [comment]
You need to replace your cards.db with mine, and rename it to cards.db

**Comment by geofflangenderfer** [comment]
To run locally, I replaced db/cards.db with cards-jwasham.db :

`cp cards-jwasham.db db/cards.db`
