### ISSUE TITLE
username / password not same as config.txt when using docker 

### ISSUE THREAD

**Issue by pauldhawk** [jwasham/computer-science-flash-cards#3]
issue: The login page would not take my password in the config.txt file. 

found workaround - used the user / password in the flash_cards.py file:
    USERNAME='admin',
    PASSWORD='default'

is there a way to have the config file work, or does the readme just need to be updated?

**Comment by jwasham** [comment]
Hi Paul,
@tinpee Would you mind answering? You know more about the docker setup than I.

**Comment by hienphamlabs** [comment]
I forgot that @jwasham use system service and he added an ENV variable to provider where is the config file. So i added this env var to docker entry. 
Now work :)
#4

**Comment by joshash1102** [comment]
I tried the Flask method and I am getting similar issue. "Invalid username" even though I enter exact  username as in config.txt

**Comment by hienphamlabs** [comment]
Hi @joshash1102 
Are you delete old image and build a new ?.

**Comment by joshash1102** [comment]
I just cloned the entire repository(less than an hour ago). I see the latest commit 5 hours ago. Do I still need to delete the old image? If yes, how exactly? Is checking out again sufficient(Sorry pretty new to docker/image, etc)

**Comment by hienphamlabs** [comment]
@joshash1102 Yes, you should the remove old container, image and build a new one.
- `docker stop cs-flash-cards && docker rm cs-flash-cards && docker rmi cs-flash-cards`
- Clone this repo, edit username and password you want.
- Build image: `docker build . -t cs-flash-cards`
- Run container: `docker run -d -p 8000:8000 --name cs-flash-cards cs-flash-cards`
- Go your browser and type `http://localhost:8000`

Of course you could just rebuild a new image, but this action would tag old image with none, so a better solution is delete old and build a new one.
Hope this help :)

**Comment by joshash1102** [comment]
But I am not using docker. I was using the first Flask method described in ReadMe. I am on MAC OSX and I was running into lot of issues installing Docker. Can you explain what is to be done for that?

**Comment by hienphamlabs** [comment]
@joshash1102, The first method is designed for running on Linux/Ubuntu. I'm wondering could it work in OSX ? You could try docker, it's cross platform and easy to run :)
@jwasham Can you help this problem?

**Comment by joshash1102** [comment]
You are right. I did face some issues but was able to find some work around. For example systemctl=> replaced with launchctl.

**Comment by pauldhawk** [comment]
confirming the fix works for me. i'm using docker and on a mac. thanks guys

**Comment by hienphamlabs** [comment]
@pauldhawk You're welcome ! :)
@joshash1102 You should install docker and try to use.

**Comment by jwasham** [comment]
Hi, @joshash1102 I haven't tried it on a Mac, so I'm unaware of incompatibilities or how to fix them. I'm much stronger with Linux than I am with Mac. I'm running it on Ubuntu on a cloud server.

It looks like you found a way to make it work, correct? It was just a matter of using a different tool for starting/stopping services?

**Comment by joshash1102** [comment]
yes, I used launchctl instead of systemctl. There were some minor changes in Flask install too.
It is working but I have to use default username and password

**Comment by jwasham** [comment]
I made some edits to the readme about changing the config. If you don't mind, please update the readme with the Mac instructions (if you can remember all the fixes).

**Comment by joshash1102** [comment]
sure..will try to update whatever I can remember.

**Comment by iamshm** [comment]
Hey @joshash1102  @jwasham 
I'm trying to build the image on a windows machine.
Using this command : - docker build . -t cs-flash-cards
![Screenshot (95)](https://user-images.githubusercontent.com/43462941/80418870-b39d0a80-88f5-11ea-8799-9208ca2a8743.png)
And the build is not proceeding.
I'm new to docker.
