### ISSUE TITLE
standard_init_linux.go:185: exec user process caused "no such file or directory" on Docker on Windows

### ISSUE THREAD

**Issue by alikor** [jwasham/computer-science-flash-cards#30]
Hello I get the following error when attempting to launch the docker on a windows box

standard_init_linux.go:185: exec user process caused "no such file or directory"

I'm not sure if its windows specific

**Comment by alikor** [comment]
Somehow line endings on entrypoint.sh had been changed to windows line entry which broke everything

**Comment by jwasham** [comment]
Feel free to publish a PR.

**Comment by kuskmen** [comment]
My lines are correctly only lf and again I receive the same error, someone knows anything about it?

**Comment by mehmetsezgin** [comment]
I added line below after COPY. It works fine on Windows 10 and Docker Version 18.06.1-ce.
RUN sed -i 's/\r$//' /entrypoint.sh

**Comment by jwasham** [comment]
Thank you! Closing this issue.
