### ISSUE TITLE
Running in docker container with backup file typo

### ISSUE THREAD

**Issue by sourabh3b** [jwasham/computer-science-flash-cards#33]
In the section **How to run with Docker**, there's a typo in second part. 
It's written (note: there's `:` written after -v flag, it shouldn't be there)

`docker run -d -p 8000:8000 --name cs-flash-cards -v :<path_to_folder_contains_cards_db>:/src/db cs-flash-cards`

It should be 
`docker run -d -p 8000:8000 --name cs-flash-cards -v <path_to_folder_contains_cards_db>:/src/db cs-flash-cards
`

**Comment by jwasham** [comment]
Thanks for finding that! Please do a pull request with the fix.

**Comment by sourabh3b** [comment]
sure, just raised a PR with fix.

**Comment by jwasham** [comment]
Merged. Thank you!
