### ISSUE TITLE
Request: unpack the dbs into a format that can accept a diff

### ISSUE THREAD

**Issue by beck** [jwasham/computer-science-flash-cards#36]
I noticed an error in one question:

> Using bitwise operations, how would you test that a number is a power of 2?
> bool isPowerOfTwo = (x & (x - 1);

The solution should be:
> (x & (x - 1)) == 0

**Comment by jwasham** [comment]
That's a good catch. 
I've not worked on this project in a long time, and adding support for a diffable format is not something I have time for right now. Sorry!

**Comment by jwasham** [comment]
Closing due to age of issue.
