### ISSUE TITLE
Install in local failed

### ISSUE THREAD

**Issue by catwithtudou** [jwasham/computer-science-flash-cards#41]
Using cached https://files.pythonhosted.org/packages/12/3f/557356b60d8e59a1cce62ffc07ecc03e4f8a202c86adae34d895826281fb/pycurl-7.43.0.tar.gz
    ERROR: Command errored out with exit status 10:

**Comment by hoangminhtoan** [comment]
- before installing `pycurl` you need to install essential packages `sudo apt install libcurl4-openssl-dev libssl-dev`
- I removed all specific version of every package and it worked
