### ISSUE TITLE
Any plans to make Flash cards easily printable?

### ISSUE THREAD

**Issue by joshash1102** [jwasham/computer-science-flash-cards#5]
First of all, thank you for a great tool. It is pretty useful :)

Are there any plans to Make the cards printable in a format such that, they can easily be converted into physical flash cards?

**Comment by hienphamlabs** [comment]
You mean we can download as pdf with 2 page or 2 image or print directly for each flashcard?

**Comment by jwasham** [comment]
Sorry, I don't have any plans for that.
Here are some options you could investigate: https://www.google.com/webhp?#q=flash%20card%20print

**Comment by joshash1102** [comment]
i meant it being a bit more printer friendly, something like:
1. Someone can directly give the print command for both front and back from same console. 
2. Multiple cards on the same page to save paper
2. They will be printed in such a way that front of card will align with back on same paper

As I said, just a suggestion and "good to have" features. What you guys have done is already great and thanks for making it available for everyone:)

**Comment by joshash1102** [comment]
@jwasham 
No problem. Was just curious. You are right. we can easily use those 3rd party tools.
Cheers!!
