### ISSUE TITLE
How to use your db?

### ISSUE THREAD

**Issue by Desperado1001** [jwasham/computer-science-flash-cards#56]
I have changed database configuration like this:
`app.config.update(dict(
    DATABASE=os.path.join(app.root_path, 'db', 'cards-jwasham.db'),
    SECRET_KEY='development key',
    USERNAME='admin',
    PASSWORD='default'
))`
but I couldn't get you cards.

**Comment by hoangminhtoan** [comment]
- `schema.sql` runs query to delete `cards` table before re-creating empty ones.
- Change into `SELECT * FROM cards;`
- Run `initdb()` for the first time, then comment it

**Comment by jwasham** [comment]
Closing due to age of issue.
