### ISSUE TITLE
How to backup cards db from Docker?

### ISSUE THREAD

**Issue by jwasham** [jwasham/computer-science-flash-cards#6]
For @tinpee 
For those who use the Docker method, how can people find and backup their card db after making edits?

Since Docker containers are meant to be somewhat disposable, I always try to find a way to backup databases resident in containers. For example, my blog runs in a container, but I can ssh tunnel to the host, connect to the database, and use a MySQL tool to do a SQL dump.

**Comment by hienphamlabs** [comment]
We are using sqlite for db, so the easiest way is copy the file `cards.db` and store it.
`docker cp <contiainer_name>:/src/cards.db /path/to/save`

**Comment by jwasham** [comment]
Thank you!
