### ISSUE TITLE
500 Internal Server Error after Logging In

### ISSUE THREAD

**Issue by mdvsh** [jwasham/computer-science-flash-cards#69]
After following the steps in thoroughly to setup the app (working nginx and uwsgi configs), the site is able to load the login page. 
However on logging through the username and password previously changed in `config.txt`, the site returns a **500 Internal Server Error.** on route `(/cards)`

`/general`
![image](https://user-images.githubusercontent.com/33770878/115882950-e3c8ac00-a46a-11eb-8bae-285e84277c58.png)

Though I am able to go back to the login route and can see that my login state is indeed true as shown by the updated navbar.
![image](https://user-images.githubusercontent.com/33770878/115883077-035fd480-a46b-11eb-84d2-9eb2fafa9933.png)

Still, all the links (/cards, /general, /code) give a **500 Internal Server Error**.
Interestingly, the logout route still works and I am able to log out successfully.

![image](https://user-images.githubusercontent.com/33770878/115883288-43bf5280-a46b-11eb-8768-5d383005396d.png)

Is there any issue with the memory allocated to this app or have I done something wrong? Kindly tell. 
Thank you

**Comment by mdvsh** [comment]
I realised that I hadn't initialised the database. Maybe the author can add this step (currently only commented in `flash_cards.py`) in the README as well.

Closing...

**Comment by jwasham** [comment]
Feel free to add it and make a pull request!
