### ISSUE TITLE
Could I share the flashcards to Anki Share Deck?

### ISSUE THREAD

**Issue by JackKuo-tw** [jwasham/computer-science-flash-cards#74]
For convenience, people who want to import flashcards to Anki can omit the Python transformation step.

If you don't use Anki, can I do this for you? Thanks.

**Comment by jwasham** [comment]
That's fine with me. 
One set for each for:
* cards-jwasham.db
* cards-jwasham-extreme.db

That way people can choose which they want.

There is a script on the readme to convert the db to anki.

**Comment by JackKuo-tw** [comment]
So great! Thanks for your authorization & kind reminder.
Here are 2 Anki shared decks:
1. [computer science flash cards - jwasham (basic)](https://ankiweb.net/shared/info/1782040640)
2. [computer science flash cards - jwasham (extreme)](https://ankiweb.net/shared/info/1691396127)

**Comment by jwasham** [comment]
No need to close the issue. Let's do this!
The link to the basic set is broken.

**Comment by JackKuo-tw** [comment]
I've updated the link of **basic** 10 hours ago, maybe you should refresh the page and click it again.
Is there anything to do? How about adding these links to README?

**Comment by jwasham** [comment]
They are working 😄  
Wow, looking back even some of the basic ones are too much to know. 

Anyway, I'll add these to the README. Will close this when done. Thank you!

**Comment by jwasham** [comment]
Done! 
https://github.com/jwasham/computer-science-flash-cards/commit/cfffd2006be367176bfc4ce0617b50edb58ebd6f
Thank you!
